l_russian:
 # General 
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$ сек."
 SETTING_VALUE_MINUTES:0 "$VALUE$ хв."
 # Graphics
 SETTING_RENDERER:0 "Рендеринг"
 SETTING_VSYNC:0 "Вертикальна синхронізація"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!Синхронізує частоту кадрів гри та монітора, зменшуючи розриви зображення на екрані.\n\nВимкнення цього параметра може підвищити продуктивність."
 SETTING_PORTRAIT_MULTI_SAMPLING:0 "Згладжування портретів"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Використання згладжування за технологією Alpha-To-Coverage для більш плавного накладання волосся.\n\nЗниження параметра може підвищити продуктивність."
 SETTING_MULTI_SAMPLING:0 "Згладжування (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!При використанні згладжування з множинною вибіркою (MSAA) краї зображення стають гладкішими.\n\nЗниження параметра може підвищити продуктивність."
 SETTING_ANTI_ALIASING:0 "Згладжування"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!При використанні згладжування краю зображення будуть менш різкими.\n\nРекомендуємо використовувати FXAA."
 OPTION_ANTI_ALIASING_DISABLED:0 "Вимк."
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_ANISOTROPIC_FILTERING:0 "Фільтрування текстур"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Використання анізотропної фільтрації покращує зовнішній вигляд текстурованих поверхонь.\n\nЗниження параметра може підвищити продуктивність."
 SETTING_FULLSCREEN_RESOLUTION:0 "Дозвол"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:3 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Якість зображення в грі.\n\nЗниження роздільної здатності може підвищити продуктивність.\n\n#X Дозволи з непідтримуваним співвідношенням сторін можуть призвести до виходу елементів"
 SETTING_WINDOWED_RESOLUTION:0 "Роздільна здатність у віконному режимі"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:2 "#T $SETTING_WINDOWED_RESOLUTION$\n#!Якщо гра запущена у віконному режимі — визначає дозвіл вікна.\n\nНеобхідно використовувати формат #b ЧІСЛО#!x#b ЧИСЛО#!. непідтримуваним співвідношенням сторін може призвести до того, що інтерфейс виявиться поза екраном#!"
 SETTING_RENDER_SCALE:0 "Розмір рендеру"
 SETTING_RENDER_SCALE_TOOLTIP:0 "#T $SETTING_RENDER_SCALE$#!\nРозмір дозволу рендеру в грі щодо дозволу екрана за вирахуванням інтерфейсу.\n\nЗниження параметра може підвищити продуктивність, але знизить якість зображення, тоді як збільшення понад 100% ймовірно, зменшить продуктивність."
 SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
 SETTING_DISPLAY:0 "Монітор"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!Якщо у вашого комп'ютера кілька моніторів, виберіть той, який буде використовуватися в грі."
 SETTING_GRAPHICS_DEVICE:0 "Відеокарта"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!Виберіть, яка відеокарта буде використовуватися в грі.\n\nВикористання інтегрованої відеокарти або програмного рендерингу може знизити продуктивність."
 SETTING_SHADOW_MAP_RESOLUTION:0 "Якість тіней"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Якщо тіні включені, параметр визначає дозвіл, з яким накладаються карти тіней.\n\nЗниження параметра може підвищити продуктивність."
 SETTING_DISPLAY_MODE:0 "Режим відображення"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!Визначає, як буде відображатися гра на вашому екрані"
 SETTING_BLOOM:0 "Свічення"
 SETTING_MESH_LOD_BIAS:0 "Якість деталізації сітки"
 SETTING_MESH_LOD_FADE:0 "Зменшення деталізації сітки"
 SETTING_TERRAIN_SMOOTHING:1 "Згладжування ландшафту"
 OPTION_FULLSCREEN:0 "Повноекранний"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!Відображати гру на весь екран. Параметри розширення будуть впливати на чіткість зображення."
 OPTION_WINDOWED:0 "Віконний режим"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!Відображати гру у вікні. Налаштування роздільної здатності змінюють розмір вікна."
 OPTION_DISABLED:1 "Вимк."
 OPTION_OFF:0 "Вимк."
 OPTION_LOW:0 "Низький"
 OPTION_MEDIUM:0 "Середній"
 OPTION_HIGH:0 "Високий"
 OPTION_ULTRA:1 "Дуже високий"
 OPTION_CUSTOM:0 "Користувача"
 OPTION_DEFAULT:1 "За замовчуванням"
 SETTINGS_CATEGORY_UI:0 "Інтерфейс"
 SETTINGS_CATEGORY_GAME:0 "Гра"
 SETTING_TEXTURE_QUALITY:1 "Якість текстур"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\nРоздільна здатність завантажених текстур.\n\nЗниження параметра може підвищити продуктивність."
 SETTING_QUALITY:0 "Збережена настройка якості"
 SETTING_SFX:0 "Звукові ефекти"
 SETTING_UI:0 "Інтерфейс"
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!Виберіть збережений параметр у додаткових налаштуваннях графіки внизу.\n\nНизьке значення збереженого параметра підвищить продуктивність."
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!Включає ефект свічення, при якому дуже яскраве світло переноситься на інші частини зображення.\n\nВимкнення параметра може підвищити продуктивність."
 SETTING_DOF_TOOLTIP:0 "#T $SETTING_DOF$\n#!Включає глибину поля, що симулює об'єктив камери, розмиває частини зображення, що не знаходяться у фокусі.\n\nВимкнення параметра може підвищити продуктивність."
 SETTING_MAP_SSAO_TOOLTIP:0 "#T $SETTING_MAP_SSAO$\n#!Визначає, чи буде застосовуватися до карти перегородження навколишнього світла в екранному просторі.\n\nВимкнення параметра може підвищити продуктивність."
 SETTING_REFRACTION_TOOLTIP:0 "Відображати (або ні) відображення на воді."
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\nЯкість відображень на воді (якщо вони відображаються).\n\nЗниження параметра може підвищити продуктивність."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\nМаксимальний рівень якості відображення об'єктів на карті (будівлі тощо).\n\nЗниження параметра може підвищити продуктивність."
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\nЯкість деталізації об'єктів на карті (підрозділи тощо).\n\nЗниження параметра може підвищити продуктивність."
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!Якщо цей параметр увімкнено, у тривимірних моделях відбувається плавний перехід між різними рівнями деталізації при зміні масштабу.\n\nВимкнення параметра може підвищити продуктивність."
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "Спосіб показувати на карті назви міст та провінцій."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Включати (або ні) до кордонів держави на карті непрохідні ділянки."
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\nМова інтерфейсу користувача."
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Адреса вашої електронної пошти для облікового запису Paradox"
 SETTING_FRAMERATE_CAP:1 "Обмеження кількості кадрів"
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\nОбмеження числа кадрів на секунду, яке відображатиме гра.\n\nЗниження параметра може скоротити споживання електроенергії."
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 SETTING_TEXTURE_STREAMING:0 "Стрімінг текстур"
 SETTING_TEXTURE_STREAMING_CACHE:0 "Розмір кешу стрімінгу текстур"
 SETTING_VALUE_MB:0 "$VALUE$ МБ"
 # GUI
 SETTING_ANIMATION_SPEED:0 "Швидкість анімації"
  SETTING_GUI_SCALING:0 "Масштабування інтерфейсу"
  SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!Задає масштаб інтерфейсу користувача. Зручно для великих дозволів екрана.\n\n#X Занадто високе значення параметра призведе до того, що елементи інтерфейсу не будуть розміщуватися на екрані.#!"
 # System
 SETTING_SCREEN_EDGE_SCROLL_MODE:0 "Переміщення мишею"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE:0 "Вільний"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS:0 "8 напрямків"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED:0 "Вимк."
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP:0 "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nПоведінка камери при переміщенні мишею."
 SETTING_SCROLL_SPEED:1 "Швидкість перетягування"
 SETTING_SCROLL_SPEED_TOOLTIP:0 "#T $SETTING_SCROLL_SPEED$#!\nВизначає швидкість переміщення карти за допомогою клавіатури або миші."
 SETTING_CAMERA_ROTATION_SPEED:1 "Швидкість обертання камери"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP:0 "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nШвидкість обертання камери."
 SETTING_ZOOM_SPEED:1 "Швидкість наближення"
 SETTING_ZOOM_SPEED_TOOLTIP:0 "#T $SETTING_ZOOM_SPEED$#!\nШвидкість наближення камери."
 SETTING_MOUSE_CURSOR_ZOOM_MODE:0 "Поведінка наближення"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR:0 "Щодо курсору"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR:0 "Наближення до курсора"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR:0 "Ігнорувати курсор"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP:0 "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nПоведінка камери при наближенні та віддаленні щодо курсору."
 SETTING_INPUT_DEVICE:0 "Пристрій введення"
 SETTING_EDITOR:0 "Редактор"
 SETTING_EDITOR_POSTFIX:0 "Постфікс для команди редактора"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Команда відкриття редактора"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "Подивитися журнал команд"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "Команда відкриття редактора коду"
 SETTING_GRACEFUL_EXIT:0 "Вихід при помилці"
 SETTING_LANGUAGE:0 "Мова"
 MOUSE_AND_KEYBOARD:0 "Клавіатура та миша"
 GAMEPAD:0 "Геймпад"
 SETTING_MULTISAMPLING_DISABLED:0 "Відключено"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED:0 "Відключено"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Відключено"
 # Editor
 SETTING_CAMERA_TILT:0 "Нахил камери"
 SETTING_CAMERA_STRATEGY:0 "Тип камери"
 SETTING_CENTERED_ZOOM_IN:0 "Наближення до центрування"
 SETTING_CAMERA_SPEED:0 "Швидкість камери"
 CAMERA_TABLETOP:0 "Настільний вигляд"
 CAMERA_FPS:0 "Від першої особи"
 CAMERA_WASD:0 "Стиль WASD"
 # Audio
 SETTING_Music:0 "Музика"
 SETTING_Ambient:0 "Звуковий супровід"
 SETTING_Effects:0 "Ефекти"
 SETTING_Master:0 "Загальний рівень"
 SETTING_Master_TOOLTIP:0 "#T Основна гучність\n#!Встановлює гучність всіх звуків у грі."
 SETTING_Music_TOOLTIP:0 "#T Гучність музики\n#!Встановлює гучність музики."
 SETTING_Ambient_TOOLTIP:0 "#T Звуковий супровід\n#!Встановлює гучність звукового супроводу."
 SETTING_SFX_TOOLTIP:0 "#T Звукові ефекти\n#!Встановлює рівень гучності звукових ефектів (бою і так далі)."
 SETTING_UI_TOOLTIP:0 "#T Інтерфейс\n#!Встановлює рівень гучності звуків інтерфейсу."
 SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "Налагодження журналу рівнів"
 SETTING_AUDIO_DEVICE_PROFILE:0 "Аудіопрофіль"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP:0 "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Виберіть аудіопрофіль під свої пристрої."
 SETTING_AUDIO_OPTION_SPEAKERS:0 "Колонки"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Стандартне поєднання для колонок."
 SETTING_AUDIO_OPTION_HEADPHONES:0 "Навушники"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Поєднання, що підходить для навушників."
 SETTING_AUDIO_OPTION_TV:0 "ТВ"
 SETTING_AUDIO_OPTION_TV_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_TV$\n#!Поєднання для колонок, вбудованих у телевізор або монітор."
 SETTING_AUDIO_OPTION_NIGHTMODE:0 "Нічний режим"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Приглушує звук для гри вночі, принижуючи високі частоти та знижуючи дальність динаміків."
 # Game
 SETTING_AUTOSAVE:0 "Інтервал автозбережень"
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!Вказує частоту автозбереження гри."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Записувати автозбереження в хмару (або ні)."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Завжди розгортати ігрову камеру на північ чи ні."
 NO_AUTOSAVE:0 "Без автозбережень"
 # Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED:0 "Швидкість передачі файлів"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP:0 "#T $File Transfer Speed$\n#!Задає максимальну швидкість передачі файлів збереженої гри в лобі мережевої гри.\n\nЗниження цього параметра може покращити стабільність мережі при підключенні до мережних ігор, але це негативно позначиться на часі завантаження файлів."
 # Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES:0 "Автозбереження в редакторі карток (хв.)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP:0 "Частота автозбережень у редакторі карток (хв.)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE:0 "Переміщення вузлів"
 # Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY:0 "Спеціальні можливості"
 SETTING_COLOR_BLIND_MODE:0 "Режим помітних кольорів"
 SETTING_COLOR_BLIND_MODE_TOOLTIP:0 "#T $SETTING_COLOR_BLIND_MODE$\n#!Замінює кольори в грі на більш помітні для людей, які страждають на колірну сліпоту."

# === [LocEditor:OrphanedKeys] Keys that do not exist in English ===
 SETTING_MOUSE_PANNING:0 "Прокручування на краю екрана"
 SETTING_MOUSE_PANNING_TOOLTIP:0 "#T $SETTING_MOUSE_PANNING$\n#!Визначає, чи повинна карта прокручуватися, якщо курсор миші знаходиться на краю екрана або вікна."