	l_russian:
 SETTING_AUTOSAVE_TO_CLOUD:0 "Автоматичне збереження у хмарі"
 SETTING_SAVE_FILE_FORMAT:0 "Стандартний формат збереження"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "Цей варіант переписується в режимі "Залізна воля", хмарному режимі та режимі налагодження"
 OPTION_SAVE_FILE_TEXT:0 "Текст"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "Стиснутий текст"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "Стиснутий двійковий код"
 SETTING_TOOLTIP_MODE:0 "Режим спливаючих підказок"
 SETTING_TOOLTIP_MODE_TOOLTIP:1 "#T $SETTING_TOOLTIP_MODE$#!\nВиберіть метод закріплення підказки:\n #b Поведінка миші#! - Закріплює під час руху курсора в бік підказки.\n #b Блок за таймером#! - Закріплює через о. n #b Ручний блок #! - Закріплюється при натисканні середньої кнопки миші."
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "Без закріплення"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Поведінка миші"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "Ручний блок (закріплення мишею)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "Блок по таймеру (закріплення мишею)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "Ручний блок"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "Блок по таймеру"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nВстановлює затримку перед появою спливаючої підказки при наведенні на відповідний елемент."
 SETTING_TOOLTIP_DELAY:0 "Показати затримку"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Затримка розблокування"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nЗатримка перед розблокуванням спливаючих підказок."
 SETTING_TOOLTIP_LOCK_TIME:0 "Затримка блокування"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nЗатримка перед блокуванням спливаючих підказок."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Затримка відкриття"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nЗатримка перед блокуванням спливаючих підказок, якщо одна підказка вже відкрита."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Розширені"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Загальні"
 SETTINGS_CATEGORY_SFX:0 "Особливі звукові ефекти"
 SETTINGS_CATEGORY_LANGUAGE:0 "Мова"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Збереження гри"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Налаштування підказок"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Керування карткою"
 SETTING_SHADER_QUALITY:0 "Якість шейдерів"
 SETTING_SHADER_QUALITY_TOOLTIP:1 "#T Якість шейдерів\n#!Визначає якість шейдерів та ефектів.\n\n#T Висока:#! Підвищує якість ряду ефектів шейдерів ціною зниження продуктивності.\n\n#T Середнє:#! зовнішнього вигляду гри за задумом розробників.\n\n#T Низьке:#! Цей варіант призначений для слабких машин. Ми не рекомендуємо використовувати його через падіння якості графіки.
 SETTING_SHOW_NUDITY:0 "Показувати наготу"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nЗображення оголених персонажів."
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Портрети"
  Audio
 SETTING_MUSIC:0 "Музика"
 SETTING_AMBIENT:0 "Звуковий супровід"
 SETTING_MUSIC_TOOLTIP:0 "#T Гучність музики\n#!Встановлює гучність музики."
 SETTING_AMBIENT_TOOLTIP:0 "#T Звуковий супровід\n#!Встановлює гучність звукового супроводу."

 color_blind_mode_test:0 "Тест"